#!/usr/bin/env bash
# Set the input field separator to ":"
IFS=":"
# Read the /etc/passwd file line by line
while read -r username x uid gid info homedir shell;
do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell."
    echo "User ID's place is protected by the passcode $x, more info about the user here: $info"
    echo
done < /etc/passwd
