#!/usr/bin/env bash
# displays numbers from 1 to 20
i=1
while [ "$i" -le 20 ]
do 
       case $i in
            4)
                echo "$i and bad luck from China"
                ;;
            9)
                echo "$i and bad luck from Japan"
                ;;
            17) 
                echo "$i and bad luck from Italy"
                ;;
            *)
                echo $i
                ;;
       esac
           $(( i+1 ))
done
