#!/usr/bin/env bash
# Displays the content of the current directory in a list format and where only after the first dash is displayed
echo Directories
for item in * 
do
    if [ -d $item ] 
     then
        echo "$item"
    fi
done

echo Files
for item in *
do
	if [ -f $item ]
	then
		echo "$item"
	fi	

done	
