#!/usr/bin/env bash
# Iterate over files in the current directory
for file in *; 
do
    # Check if it's a regular file and not a hidden file
    if [ -f "$file" ] && [[ ! "$file" == .* ]]; 
     then
        # Extract the part after the first dash
        name=$(echo "$file" | cut -d'-' -f2-)
        # Print the modified name
        echo "$name"
    fi
done
