#!/usr/bin/env bash
# Displays the content of the current directory in a list format and where only after the first dash is displayed
for item in * 
do
    if [ -d $item ] 
     then
        echo "$item"
    fi
done
