#!/usr/bin/env bash
# Define the signal handlers
trap 'echo "I hate the kill command";  rm -f /var/run/myscript.pid; exit 1' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit 1' SIGINT
trap 'echo "Goodbye!"; rm -f /var/run/myscript.pid; exit 1' SIGQUIT
# Get the PID and write it to the file
echo $$ > /var/run/myscript.pid
# Display messages indefinitely
while true;
do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
