#!/usr/bin/env bash
# Find and stop the process using pkill
pkill -f "4-to_infinity_and_beyond"
# Check if the process is still running
if pgrep -f "4-to_infinity_and_beyond" > /dev/null; 
then
    echo "Failed to stop 4-to_infinity_and_beyond process."
else
    echo "4-to_infinity_and_beyond process has been stopped."
fi
